version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    #container_name: nolevel-app
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - rede_gera

networks:
  rede_gera:
    external: true